## 
## Travis Unit Testing settings
##

## LLVM/CLang settings based on the FTL project .travis.yml (https://github.com/beark/ftl) 
## 
## There are no unit tests currently aviable, except some debugging tests on main.cpp (Unstable and susceptible to be modified
## or even broken). Since this is a C++ metaprogramming library, successfull compilation is interpreted as the tests successfully
## passed (If not, the static asserts fail and the compilation fails). 

compiler:
  - clang

# Setup repos etc before installation
before_install:
  - if [ "$CXX" == "clang++" -a "$CPP14" == "1" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq

# Install dependencies
install:
  # install biicode:
  
  - wget https://s3.amazonaws.com/biibinaries/release/1.3.3/bii-ubuntu32_1_3_3.deb 
  - (! sudo dpkg -i bii-ubuntu32_1_3_3.deb ) && sudo apt-get -f install

  # install clang-3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi

  - if [ "$CXX" == "clang++" ]; then cwd=$(pwd); fi

  # Install libc++ if tests are run with clang++
  - if [ "$CXX" == "clang++" -a "$CPP14" == "0" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk@181765 libcxx; fi

  - if [ "$CXX" == "clang++" ]; then cd libcxx/lib && bash buildit; fi
  - if [ "$CXX" == "clang++" ]; then sudo cp ./libc++.so.1.0 /usr/lib/; fi
  - if [ "$CXX" == "clang++" ]; then sudo mkdir /usr/include/c++/v1; fi
  - if [ "$CXX" == "clang++" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/; fi
  - if [ "$CXX" == "clang++" ]; then cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so; fi
  - if [ "$CXX" == "clang++" ]; then sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd; fi

  - if [ "$CXX" == "clang++" ]; then CXX=clang++-3.4; fi

before_script:
  - export CXX=clang++

# command to run tests
script: 
  - bii find
  - bii work
  - bii cpp:build
  - ./bin/manu343726_turbo_main_main 
